### ISSUE TITLE
Ubuntu Server 22.04 with replace-kernel and add-autoinstall-config stuck on `mouting /dev/sr0 on /cdrom failed: No such device`

### ISSUE THREAD

**Issue by cfroystad** [mwhudson/livefs-editor#29]
### Current behavior

After replacing the bundled kernel with the hwe version on Ubuntu 22.04 (using replace-kernel) and adding an autoinstall script (using add-autoinstall-config), the installer gets stuck after casper-premount.

Error message: 'mount: mounting /dev/sr0 on /cdrom failed: No such device'

If I remove either of `add-autoinstall-config` or `replace-kernel`, booting and installation works fine as expected. However, the combination results in installation getting stuck on this error.

### Expected behavior

Being able to both replace the kernel and use autoinstall together.

### Reproduce

```yaml
- name: replace-kernel
  flavor: generic-hwe-22.04

- name: add-autoinstall-config
  autoinstall_config: autoinstall.yaml
```
_pre-seed.yaml:_

```yaml
#cloud-config
autoinstall:
  user-data:
    disable_root: true
    timezone: UTC
    package_upgrade: false
    users:
      - name: user
        primary_group: users
        groups: audio video
        lock_passwd: false
        # echo <PASSWORD> | openssl passwd -1 -stdin
        passwd: "adfasdfadsfadsfadsfasdfasdfadsfad"
        shell: /bin/bash
        chpasswd: { expire: False }
        sudo: false
```

![image](https://user-images.githubusercontent.com/1038204/215986326-b258b0f0-96a7-440e-8c71-816d7abb87dc.png)

### Meta

**Original ISO Version:** Ubuntu Server 22.04 ([daily build](http://cdimage.ubuntu.com/cdimage/ubuntu-server/jammy/daily-live/pending/jammy-live-server-amd64.iso), downloaded 31.01.2023)
**livefs-editor hash:** 2dd0179e25a2366067906979579a1cd797fd1b37

**Comment by dbungert** [comment]
```
#cloud-config
autoinstall:
  user-data:
    ...
```
Totally unrelated to the bug report but I think you need a `version: 1` in there.
```
#cloud-config
autoinstall:
  version: 1
  user-data:
    ...
```
